//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceAttend
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceLog
    {
        public long Id { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string EventType { get; set; }
        public string Source { get; set; }
        public string EmployeeFullName { get; set; }
        public string Department { get; set; }
        public int OfficeId { get; set; }
        public string OfficeType { get; set; }
        public string OfficeName { get; set; }
        public Nullable<double> GPSLatitude { get; set; }
        public Nullable<double> GPSLongitude { get; set; }
        public Nullable<double> GPSAccuracy { get; set; }
        public string WiFiSSID { get; set; }
        public bool LocationVerified { get; set; }
        public string LocationError { get; set; }
        public Nullable<double> FaceDistance { get; set; }
        public Nullable<double> FaceSimilarity { get; set; }
        public Nullable<double> MatchThreshold { get; set; }
        public Nullable<double> LivenessScore { get; set; }
        public string LivenessResult { get; set; }
        public string LivenessError { get; set; }
        public string ClientIP { get; set; }
        public string UserAgent { get; set; }
        public bool NeedsReview { get; set; }
        public string Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Office Office { get; set; }
    }
}
