//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceAttend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string Fingerprint { get; set; }
        public string DeviceName { get; set; }
        public string DeviceType { get; set; }
        public string Status { get; set; }
        public System.DateTime RegisteredAt { get; set; }
        public string RegisteredFromIp { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> LastUsedAt { get; set; }
        public int UseCount { get; set; }
        public string DeviceToken { get; set; }
        public Nullable<System.DateTime> TokenExpiresAt { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
