//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceAttend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AttendanceLogs = new HashSet<AttendanceLog>();
        }
    
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public string Department { get; set; }
        public int OfficeId { get; set; }
        public bool IsFlexi { get; set; }
        public bool IsActive { get; set; }
        public string FaceEncodingBase64 { get; set; }
        public Nullable<System.DateTime> EnrolledDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Position { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceLog> AttendanceLogs { get; set; }
        public virtual Office Office { get; set; }
    }
}
