//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceAttend
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FaceAttendDBEntities : DbContext
    {
        public FaceAttendDBEntities()
            : base(Services.Data.FaceAttendConnectionFactory.GetEntityConnectionString())
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminAuditLog> AdminAuditLogs { get; set; }
        public virtual DbSet<AttendanceLog> AttendanceLogs { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<SystemConfiguration> SystemConfigurations { get; set; }
        public virtual DbSet<VisitorLog> VisitorLogs { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
    
        public virtual ObjectResult<sp_CheckDuplicateFace_Result> sp_CheckDuplicateFace(string excludeEmployeeId, Nullable<double> tolerance)
        {
            var excludeEmployeeIdParameter = excludeEmployeeId != null ?
                new ObjectParameter("ExcludeEmployeeId", excludeEmployeeId) :
                new ObjectParameter("ExcludeEmployeeId", typeof(string));
    
            var toleranceParameter = tolerance.HasValue ?
                new ObjectParameter("Tolerance", tolerance) :
                new ObjectParameter("Tolerance", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CheckDuplicateFace_Result>("sp_CheckDuplicateFace", excludeEmployeeIdParameter, toleranceParameter);
        }
    
        public virtual int sp_PurgeOldAttendanceLogs(Nullable<int> retentionYears, Nullable<int> batchSize, Nullable<bool> dryRun)
        {
            var retentionYearsParameter = retentionYears.HasValue ?
                new ObjectParameter("RetentionYears", retentionYears) :
                new ObjectParameter("RetentionYears", typeof(int));
    
            var batchSizeParameter = batchSize.HasValue ?
                new ObjectParameter("BatchSize", batchSize) :
                new ObjectParameter("BatchSize", typeof(int));
    
            var dryRunParameter = dryRun.HasValue ?
                new ObjectParameter("DryRun", dryRun) :
                new ObjectParameter("DryRun", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PurgeOldAttendanceLogs", retentionYearsParameter, batchSizeParameter, dryRunParameter);
        }
    }
}
