//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceAttend
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorLog
    {
        public long Id { get; set; }
        public Nullable<int> VisitorId { get; set; }
        public int OfficeId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string VisitorName { get; set; }
        public string Purpose { get; set; }
        public string Source { get; set; }
        public string ClientIP { get; set; }
        public string UserAgent { get; set; }
    
        public virtual Office Office { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
