/**
 * FaceAttend - Unified Enrollment UI Controller
 * Scripts/enrollment-ui.js
 *
 * BEHAVIOR:
 *   1. Camera starts AUTOMATICALLY when window.FaceAttendEnrollment.start() is called
 *      (triggered by showLive() in each Enroll.cshtml page controller)
 *   2. Scanning is AUTOMATIC — no manual "Start" button required
 *   3. When minFrames reached → auto-pause → SweetAlert confirmation
 *   4. User confirms → save enrollment
 *   5. User declines → resume scanning for more frames
 *
 * REQUIRES: ~/bundles/enrollment loaded in the host view
 *           (enrollment-core.js must load before this file)
 *
 * data-* attributes on #enrollRoot:
 *   data-employee-id   string   employee / visitor ID
 *   data-scan-url      string   ScanFrame endpoint URL
 *   data-enroll-url    string   Enroll endpoint URL
 *   data-redirect-url  string   redirect after success (empty = stay on page)
 *   data-mode          string   "admin" | "mobile" | "visitor"
 *   data-min-frames    int      min good frames before auto-save triggers (default 5)
 *   data-liveness-th   float    per-frame liveness threshold (default 0.75)
 */
(function () {
    'use strict';

    // ── Guard ──────────────────────────────────────────────────────────────────
    var root = document.getElementById('enrollRoot');
    if (!root) return;

    if (typeof FaceAttend === 'undefined' || typeof FaceAttend.Enrollment === 'undefined') {
        console.error('[enrollment-ui] enrollment-core.js must load before enrollment-ui.js');
        return;
    }

    // ── Config ─────────────────────────────────────────────────────────────────
    var cfg = {
        empId:       (root.getAttribute('data-employee-id') || '').trim(),
        mode:        root.getAttribute('data-mode')          || 'admin',
        scanUrl:     root.getAttribute('data-scan-url')      || '/api/scan/frame',
        enrollUrl:   root.getAttribute('data-enroll-url')    || '/api/enrollment/enroll',
        redirectUrl: root.getAttribute('data-redirect-url')  || '',
        minFrames:   parseInt(root.getAttribute('data-min-frames')   || '5',  10),
        livenessTh:  parseFloat(root.getAttribute('data-liveness-th') || '0.75')
    };

    // ── DOM ────────────────────────────────────────────────────────────────────
    function q(id) {
        return FaceAttend.Utils
            ? FaceAttend.Utils.el(id)
            : document.getElementById(id);
    }

    var ui = {
        // The video element ID is generated by _Camera.cshtml as Model.Id + "Video"
        // Since _EnrollmentComponent.cshtml sets CameraViewModel.Id = "enroll",
        // the video element has id="enrollVideo"
        video:             q('enrollVideo'),
        anglePrompt:       q('anglePrompt'),
        angleIcon:         q('angleIcon'),
        diversityDots:     root.querySelectorAll('.enroll-diversity-dot'),
        progressText:      q('enrollProgressText'),
        progressBar:       q('enrollProgressBar'),
        statusMsg:         q('enrollStatus'),
        livenessBar:       q('enrollLivenessBar'),
        livenessVal:       q('enrollLivenessVal'),
        confirmBtn:        q('enrollConfirmBtn'),
        retakeBtn:         q('enrollRetakeBtn'),
        processingOverlay: q('enrollProcessing'),
        processingStatus:  q('enrollProcessingStatus')
    };

    // Hide the legacy start button immediately — camera is auto-start
    var legacyBtn = q('enrollStartBtn');
    if (legacyBtn) legacyBtn.style.display = 'none';

    // ── Internal state ─────────────────────────────────────────────────────────
    var _running          = false;
    var _errShownOnce     = false;
    var _autoSaveShown    = false;  // Prevent multiple auto-save dialogs

    // ── Enrollment instance ────────────────────────────────────────────────────
    var enrollment = FaceAttend.Enrollment.create({
        empId:             cfg.empId,
        perFrameThreshold: cfg.livenessTh,
        scanUrl:           cfg.scanUrl,
        enrollUrl:         cfg.enrollUrl,
        redirectUrl:       cfg.redirectUrl,
        minGoodFrames:     cfg.minFrames,
        maxKeepFrames:     Math.max(8, cfg.minFrames + 3),
        enablePreview:     false
    });

    enrollment.elements.cam = ui.video;

    // Expose getEncodings for mobile wizard compatibility
    enrollment.getEncodings = function () {
        var result = [];
        for (var i = 0; i < this.goodFrames.length; i++) {
            var frame = this.goodFrames[i];
            var enc = frame.encoding || frame.enc || null;
            if (enc) result.push(enc);
        }
        return result;
    };

    // ── Determine if dark theme ────────────────────────────────────────────────
    function isDark() {
        return cfg.mode === 'mobile' ||
            cfg.mode === 'visitor' ||
            document.documentElement.getAttribute('data-theme') === 'kiosk' ||
            document.documentElement.getAttribute('data-theme') === 'dark';
    }

    // ── UI helpers ─────────────────────────────────────────────────────────────
    function setStatus(text, kind) {
        if (!ui.statusMsg) return;
        ui.statusMsg.textContent = text || '';
        ui.statusMsg.className   = 'enroll-status enroll-status--' + (kind || 'info');
    }

    function setLiveness(pct, kind) {
        if (!ui.livenessBar) return;
        var p = Math.max(0, Math.min(100, pct || 0));
        ui.livenessBar.style.width = p + '%';
        ui.livenessBar.className   = 'enroll-liveness-fill enroll-liveness-fill--' + (kind || 'info');
        if (ui.livenessVal) ui.livenessVal.textContent = p + '%';
    }

    function updateProgress(current, target) {
        var t = target || cfg.minFrames || 5;
        if (ui.progressText) ui.progressText.textContent = current + ' / ' + t + ' frames';
        if (ui.progressBar)  ui.progressBar.style.width  = Math.round((current / t) * 100) + '%';
        // Show confirm button when enough frames captured (fallback for non-auto mode)
        if (ui.confirmBtn)
            ui.confirmBtn.classList.toggle('enroll-hidden', current < cfg.minFrames);
    }

    function updateDots() {
        if (!ui.diversityDots || !ui.diversityDots.length) return;
        var captured = {};
        for (var i = 0; i < enrollment.goodFrames.length; i++) {
            var b = enrollment.goodFrames[i].poseBucket;
            if (b) captured[b] = true;
        }
        ui.diversityDots.forEach(function (dot) {
            dot.classList.toggle(
                'enroll-diversity-dot--captured',
                !!captured[dot.getAttribute('data-bucket')]
            );
        });
    }

    function showAngle(next) {
        if (!next) return;
        if (ui.anglePrompt) ui.anglePrompt.textContent = next.prompt || '';
        if (ui.angleIcon)
            ui.angleIcon.className = 'enroll-angle-icon fa-solid ' + (next.icon || 'fa-circle-dot');
    }

    function showProcessing(show, status) {
        if (!ui.processingOverlay) return;
        ui.processingOverlay.classList.toggle('enroll-hidden', !show);
        if (show && ui.processingStatus && status)
            ui.processingStatus.textContent = status;
    }

    // ── SweetAlert wrapper ─────────────────────────────────────────────────────
    function showAlert(opts) {
        if (typeof Swal !== 'undefined') {
            return Swal.fire(Object.assign({
                background: isDark() ? '#0f172a' : '#fff',
                color:      isDark() ? '#f8fafc' : '#0f172a',
                customClass: {
                    confirmButton: 'btn btn-primary me-2',
                    cancelButton:  'btn btn-outline-secondary'
                },
                buttonsStyling: false
            }, opts));
        }
        // Fallback: native confirm for success/confirm types
        if (opts.showCancelButton) {
            return Promise.resolve({ isConfirmed: window.confirm(opts.text || opts.title) });
        }
        window.alert((opts.title || '') + (opts.text ? '\n\n' + opts.text : ''));
        return Promise.resolve({ isConfirmed: true });
    }

    // ── Auto-save with SweetAlert review ──────────────────────────────────────
    function triggerAutoSave(frameCount) {
        if (_autoSaveShown) return;
        _autoSaveShown = true;

        // Pause scanning while dialog is open
        enrollment.stopAutoEnrollment();
        setStatus('Face captured! Review before saving...', 'success');

        showAlert({
            icon:             'success',
            title:            'Capture Complete!',
            text:             frameCount + ' face samples captured. Save enrollment now?',
            showCancelButton: true,
            confirmButtonText: '<i class="fa-solid fa-floppy-disk me-1"></i> Save',
            cancelButtonText:  '<i class="fa-solid fa-rotate-left me-1"></i> Capture More'
        }).then(function (result) {
            if (result && result.isConfirmed) {
                // Save enrollment
                showProcessing(true, 'Saving enrollment...');
                enrollment.performEnrollment();
            } else {
                // Resume scanning for more frames
                _autoSaveShown = false;
                enrollment.startAutoEnrollment();
                setStatus('Capturing more frames. Follow the angle prompts.', 'info');
                if (typeof enrollment.getNextAnglePrompt === 'function')
                    showAngle(enrollment.getNextAnglePrompt());
            }
        });
    }

    // ── Camera start / stop ────────────────────────────────────────────────────
    function startCamera() {
        if (_running) return;
        _running      = true;
        _errShownOnce = false;
        _autoSaveShown = false;
        setStatus('Starting camera...', 'info');

        enrollment.startCamera(ui.video)
            .then(function () {
                enrollment.startAutoEnrollment();
                if (typeof enrollment.getNextAnglePrompt === 'function')
                    showAngle(enrollment.getNextAnglePrompt());
                setStatus('Camera ready. Look straight at the camera.', 'info');
            })
            .catch(function (e) {
                _running = false;
                var msg = (e && e.message) || 'Could not access camera.';
                setStatus('Camera error: ' + msg, 'error');
                if (!_errShownOnce) {
                    _errShownOnce = true;
                    showAlert({ icon: 'error', title: 'Camera Error', text: msg });
                }
            });
    }

    function stopCamera() {
        if (!_running) return;
        _running = false;
        enrollment.stopCamera();
        setStatus('Camera stopped.', 'info');
        setLiveness(0, 'info');
    }

    // ── Enrollment callbacks ───────────────────────────────────────────────────
    enrollment.callbacks.onStatus = setStatus;

    enrollment.callbacks.onLivenessUpdate = setLiveness;

    enrollment.callbacks.onCaptureProgress = function (current, target) {
        updateProgress(current, target);
        updateDots();

        // ── AUTO-SAVE TRIGGER ─────────────────────────────────────────────────
        // When minimum frames reached, pause and show review dialog
        if (current >= cfg.minFrames && !_autoSaveShown) {
            triggerAutoSave(current);
        }

        // Forward to mobile wizard callback if present
        if (typeof window.enrollCallbacks === 'object' &&
            window.enrollCallbacks !== null &&
            typeof window.enrollCallbacks.onCaptureProgress === 'function') {
            window.enrollCallbacks.onCaptureProgress(current);
        }
    };

    enrollment.callbacks.onAngleUpdate = function (next) {
        if (next && next.bucket !== 'other') showAngle(next);
    };

    enrollment.callbacks.onEnrollmentComplete = function (count) {
        showProcessing(false);
        _running = false;

        // Show success then redirect or notify parent
        showAlert({
            icon:             'success',
            title:            'Enrollment Complete!',
            text:             count + ' face samples saved successfully.',
            confirmButtonText: 'Done'
        }).then(function () {
            if (typeof window.enrollCallbacks === 'object' && window.enrollCallbacks.onEnrollmentComplete)
                window.enrollCallbacks.onEnrollmentComplete({ vectorsSaved: count });

            if (cfg.redirectUrl) {
                window.location.href = cfg.redirectUrl;
            }
        });
    };

    enrollment.callbacks.onEnrollmentError = function (result) {
        showProcessing(false);
        _autoSaveShown = false; // Allow retry

        var msg = typeof enrollment.describeEnrollError === 'function'
            ? enrollment.describeEnrollError(result)
            : ((result && result.error) || 'Enrollment failed.');

        setStatus(msg, 'error');
        showAlert({
            icon:  'error',
            title: 'Enrollment Failed',
            html:  '<div style="font-size:.9rem">' + msg + '</div>'
        });

        if (typeof window.enrollCallbacks === 'object' && window.enrollCallbacks.onEnrollmentError)
            window.enrollCallbacks.onEnrollmentError({ message: msg });
    };

    // ── Manual button handlers (fallback / retake) ─────────────────────────────
    if (ui.confirmBtn) {
        ui.confirmBtn.addEventListener('click', function () {
            if (enrollment.goodFrames.length < cfg.minFrames) return;
            showProcessing(true, 'Processing enrollment...');
            enrollment.performEnrollment();
        });
    }

    if (ui.retakeBtn) {
        ui.retakeBtn.addEventListener('click', function () {
            enrollment.goodFrames = [];
            enrollment.passHist   = [];
            enrollment.enrolled   = false;
            enrollment.enrolling  = false;
            _autoSaveShown        = false;

            updateProgress(0, cfg.minFrames);
            updateDots();

            if (ui.confirmBtn) ui.confirmBtn.classList.add('enroll-hidden');

            enrollment.startAutoEnrollment();
            if (typeof enrollment.getNextAnglePrompt === 'function')
                showAngle(enrollment.getNextAnglePrompt());

            setStatus('Retaking. Follow the angle prompts.', 'info');
        });
    }

    // ── Init state ─────────────────────────────────────────────────────────────
    updateProgress(0, cfg.minFrames);
    setStatus('Waiting for camera...', 'info');
    if (ui.confirmBtn) ui.confirmBtn.classList.add('enroll-hidden');
    showAngle({ bucket: 'center', prompt: 'Look straight at the camera', icon: 'fa-circle-dot' });

    // Cleanup on page unload
    window.addEventListener('beforeunload', stopCamera);

    // ── Public API ─────────────────────────────────────────────────────────────
    // start() is called by showLive() in each Enroll.cshtml view
    Object.defineProperty(enrollment, 'isRunning', { get: function () { return _running; } });
    enrollment.start = startCamera;
    enrollment.stop  = stopCamera;

    window.FaceAttendEnrollment = enrollment;

})();
